import time
dauer = 0.5
testvar = input("Press enter to start")
print("      __,--------__")
time.sleep(dauer)
print("<:::::.____      (ö)':")
time.sleep(dauer)
print('       ":""          :')
time.sleep(dauer)
print("         \\          \\")
time.sleep(dauer)
print("You want")
time.sleep(dauer)
print()
print('     .---;;;;;;""""":')
time.sleep(dauer)
print("    (Ö)   |_-_|   (Ö)")
time.sleep(dauer)
print("    |               |")
time.sleep(dauer)
print("    |                |")
time.sleep(dauer)
print("    |                |")
time.sleep(dauer)
print("sum fuk?")

